import type {Metadata} from "next";
import {profile} from "@/data/profile";
export const siteUrl=(process.env.NEXT_PUBLIC_SITE_URL||"http://localhost:3000").replace(/\/$/,"");
// Production = Vercel production deploy (or a non-localhost build elsewhere). Previews/staging/local are noindex.
export const isProd=process.env.VERCEL_ENV?process.env.VERCEL_ENV==="production":process.env.NODE_ENV==="production"&&!/localhost|127\.0\.0\.1/.test(siteUrl);
export const generateCanonicalUrl=(p="/")=>p==="/"?`${siteUrl}/`:`${siteUrl}/${p.replace(/^\/|\/$/g,"")}/`;
export function generateMetadata(title:string,description:string,path:string,og:Record<string,unknown>={}):Metadata{const url=generateCanonicalUrl(path);return{title:{absolute:title},description,alternates:{canonical:url},openGraph:{title,description,url,siteName:profile.name,type:"website",...og},twitter:{card:"summary_large_image",title,description}}}
export const generatePersonSchema=()=>({"@context":"https://schema.org","@type":"Person","@id":`${siteUrl}/#person`,name:profile.name,jobTitle:profile.title,description:`${profile.name} is a WordPress and Shopify developer with 3+ years of professional experience at ${profile.company}.`,url:siteUrl,worksFor:{"@type":"Organization",name:profile.company},address:{"@type":"PostalAddress",addressLocality:"Mehsana",addressRegion:"Gujarat",addressCountry:"IN"},knowsAbout:["WordPress","Shopify","WooCommerce","Elementor","PHP","JavaScript","Shopify Liquid","Technical SEO","Schema Markup","Google Analytics 4","Google Tag Manager","Email Marketing"],...(profile.socials.length?{sameAs:profile.socials.map(x=>x.url)}:{})});
export const generateWebsiteSchema=()=>({"@context":"https://schema.org","@type":"WebSite",name:profile.name,url:siteUrl,publisher:{"@id":`${siteUrl}/#person`}});
export const generateBreadcrumbSchema=(items:[string,string][])=>({"@context":"https://schema.org","@type":"BreadcrumbList",itemListElement:[["Home","/"],...items].map(([n,p],i)=>({"@type":"ListItem",position:i+1,name:n,item:generateCanonicalUrl(p)}))});
export const generateArticleSchema=(p:{title:string;description:string;slug:string;published:string;updated?:string;image?:string})=>({"@context":"https://schema.org","@type":"BlogPosting",headline:p.title,description:p.description,author:{"@id":`${siteUrl}/#person`},datePublished:p.published,dateModified:p.updated||p.published,...(p.image?{image:p.image}:{}),mainEntityOfPage:generateCanonicalUrl(`/blog/${p.slug}/`)});
